/**
 * Lightweight i18n module for Obsidian Local REST API.
 *
 * Keys are auto-generated by morph to match the source code references.
 */

type StrMap = Record<string, string>;

/* ------------------------------------------------------------------ */
/*  English                                                            */
/* ------------------------------------------------------------------ */
const en: StrMap = {
  /* --- headings --- */
  "heading.title": "Local REST API with MCP",
  "heading.rest": "How to access via REST",
  "heading.mcp": "How to access via MCP",
  "heading.settings": "Settings",
  "heading.advanced": "Advanced settings",

  /* --- REST section --- */
  "rest.intro":
    "You can access Obsidian local REST API & MCP server via the following URLs:",
  "rest.secureName": "Encrypted (HTTPS) API URL",
  "rest.secureNote1": "Requires that ",
  "rest.secureNote2":
    " be configured as a trusted certificate authority for your browser.  See ",
  "rest.secureNote3": " for more information.",
  "rest.insecureName": "Non-encrypted (HTTP) API URL",
  "rest.authHeader1":
    "Your API key should be passed as a bearer token via the ",
  "rest.authHeader2": " header:",
  "rest.seeMore":
    "Comprehensive documentation of what API endpoints are available can be found in ",

  /* --- MCP section --- */
  "mcp.intro": "You can connect to the MCP server via the following endpoints:",
  "mcp.secureName": "Encrypted (HTTPS) MCP Endpoint",
  "mcp.secureNote1": "Requires that ",
  "mcp.secureNote2":
    " be configured as a trusted certificate authority.  See ",
  "mcp.secureNote3": " for more information.",
  "mcp.insecureName": "Non-encrypted (HTTP) MCP endpoint",
  "mcp.authHeader1":
    "Your API key should be passed as a bearer token via the ",
  "mcp.authHeader2": " header:",
  "mcp.example":
    "Example Claude code MCP configuration (for .Claude/settings.json):",
  "mcp.seeMore":
    "Configuration examples for other MCP clients can be found in ",

  /* --- common link labels --- */
  "link.certificate": "this certificate",
  "link.wiki": "wiki",
  "link.docs": "the online docs",
  "link.readme": "the project readme",

  /* --- status --- */
  "status.disabled":
    "Disabled.  You can enable this in 'Settings' below.",
  "status.enabled": "Enabled",

  /* --- certificate warnings --- */
  "status.expired": "Your certificate has expired!",
  "status.expiredDesc":
    ' You must re-generate your certificate below by pressing the "Re-generate Certificates" button below in order to connect securely to this API.',
  "status.expiringSoon":
    "Your certificate will expire in {days} day{suffix}!",
  "status.expiringDesc":
    ' You should re-generate your certificate below by pressing the "Re-generate Certificates" button below in order to continue to connect securely to this API.',
  "status.regenerate": "You should re-generate your certificate!",
  "status.regenerateDesc":
    ' Your certificate was generated using earlier standards than are currently used by Obsidian Local REST API with MCP. Some systems or tools may not accept your certificate with its current configuration, and re-generating your certificate may improve compatibility with such tools.  To re-generate your certificate, press the "Re-generate Certificates" button below.',

  /* --- settings --- */
  "setting.insecureServer": "Enable non-encrypted (HTTP) server",
  "setting.insecureServerDesc":
    "Enables a non-encrypted (HTTP) server on the port designated below.  By default this plugin requires a secure HTTPS connection, but in safe environments you may turn on the non-encrypted server to simplify interacting with the API. Interactions with the API will still require the API key shown above.  Under no circumstances is it recommended that you expose this service to the internet, especially if you turn on this feature!",
  "setting.resetCrypto": "Reset all cryptography",
  "setting.resetCryptoDesc":
    "Pressing this button will cause your certificate, private key, public key, and API key to be regenerated. This settings panel will be closed when you press this.",
  "setting.resetCryptoBtn": "Reset all crypto",
  "setting.regenerateCert": "Re-generate certificates",
  "setting.regenerateCertDesc":
    "Pressing this button will cause your certificate, private key, and public key to be re-generated, but your API key will remain unchanged. This settings panel will be closed when you press this.",
  "setting.regenerateCertBtn": "Re-generate certificates",
  "setting.restoreDefaults": "Restore default settings",
  "setting.restoreDefaultsDesc":
    "Pressing this button will reset this plugin's settings to defaults. This settings panel will be closed when you press this.",
  "setting.restoreDefaultsBtn": "Restore defaults",
  "setting.advancedSettings": "Show advanced settings",
  "setting.advancedSettingsDesc":
    "Advanced settings are dangerous and may make your environment less secure.",
  "setting.advancedSettingsHeading": "Advanced settings",
  "setting.enableSecureServer": "Enable encrypted (HTTPS) server",
  "setting.enableSecureServerDesc":
    "This controls whether the HTTPS server is enabled.  You almost certainly want to leave this switch in its default state ('on'), but may find it useful to turn this switch off for troubleshooting.",
  "setting.securePort": "Encrypted (HTTPS) server port",
  "setting.securePortDesc":
    "This configures the port on which your REST API will listen for HTTPS connections.  It is recommended that you leave this port with its default setting as tools integrating with this API may expect the default port to be in use.  Under no circumstances is it recommended that you expose this service directly to the internet.",
  "setting.insecurePort": "Non-encrypted (HTTP) server port",
  "setting.apiKey": "API key",
  "setting.certificateHostnames": "Certificate hostnames",
  "setting.certificateHostnamesDesc":
    "List of extra hostnames to add to your certificate's `subjectAltName` field. One hostname per line. You must click the \"Re-generate Certificates\" button above after changing this value for this to have an effect.  This is useful for situations in which you are accessing Obsidian from a hostname other than the host on which it is running.",
  "setting.certificate": "Certificate",
  "setting.publicKey": "Public key",
  "setting.privateKey": "Private key",
  "setting.authorizationHeader": "Authorization header",
  "setting.bindingHost": "Binding host",
  "setting.verboseLogging": "Enable verbose logging",
  "setting.verboseLoggingDesc":
    "When enabled, logs server startup messages and a one-line access log entry for every request to the browser console.",

  /* --- advanced static text --- */
  "advanced.warning":
    "The settings below are potentially dangerous and are intended for use only by people who know what they are doing. Do not change any of these settings if you do not understand what that setting is used for and what security impacts changing that setting will have.",
  "advanced.noWarranty1":
    "Use of this software is licensed to you under the MIT license, and it is important that you understand that this license provides you with no warranty. For the complete license text please see ",
  "advanced.noWarranty2": ".",

  /* --- periods for link sentence endings --- */
  "period": ".",
};

/* ------------------------------------------------------------------ */
/*  Chinese (Simplified)                                               */
/* ------------------------------------------------------------------ */
const zh: StrMap = {
  /* --- headings --- */
  "heading.title": "本地 REST API（含 MCP）",
  "heading.rest": "如何通过 REST 访问",
  "heading.mcp": "如何通过 MCP 访问",
  "heading.settings": "设置",
  "heading.advanced": "高级设置",

  /* --- REST section --- */
  "rest.intro": "您可以通过以下 URL 访问 Obsidian 本地 REST API 和 MCP 服务器：",
  "rest.secureName": "加密（HTTPS）API 地址",
  "rest.secureNote1": "需要将 ",
  "rest.secureNote2": " 配置为受浏览器信任的证书颁发机构。请参阅 ",
  "rest.secureNote3": " 了解更多信息。",
  "rest.insecureName": "非加密（HTTP）API 地址",
  "rest.authHeader1": "您的 API 密钥应通过 ",
  "rest.authHeader2": " 标头以 Bearer 令牌形式传递：",
  "rest.seeMore": "有关可用 API 端点的完整文档，请参阅 ",

  /* --- MCP section --- */
  "mcp.intro": "您可以通过以下端点连接到 MCP 服务器：",
  "mcp.secureName": "加密（HTTPS）MCP 端点",
  "mcp.secureNote1": "需要将 ",
  "mcp.secureNote2": " 配置为受信任的证书颁发机构。请参阅 ",
  "mcp.secureNote3": " 了解更多信息。",
  "mcp.insecureName": "非加密（HTTP）MCP 端点",
  "mcp.authHeader1": "您的 API 密钥应通过 ",
  "mcp.authHeader2": " 标头以 Bearer 令牌形式传递：",
  "mcp.example": "Claude Code MCP 配置示例（用于 .Claude/settings.json）：",
  "mcp.seeMore": "其他 MCP 客户端的配置示例，请参阅 ",

  /* --- common link labels --- */
  "link.certificate": "此证书",
  "link.wiki": "维基页面",
  "link.docs": "在线文档",
  "link.readme": "项目说明",

  /* --- status --- */
  "status.disabled": "已禁用。您可以在下方「设置」中启用。",
  "status.enabled": "已启用",

  /* --- certificate warnings --- */
  "status.expired": "您的证书已过期！",
  "status.expiredDesc":
    " 您必须点击下方「重新生成证书」按钮来重新生成证书，才能安全地连接到此 API。",
  "status.expiringSoon": "您的证书将在 {days} 天后过期！",
  "status.expiringDesc":
    " 您应当点击下方「重新生成证书」按钮来重新生成证书，以继续安全地连接到此 API。",
  "status.regenerate": "建议您重新生成证书！",
  "status.regenerateDesc":
    " 您的证书使用的标准低于 Obsidian 本地 REST API（含 MCP）当前使用的标准。某些系统或工具可能无法接受当前配置的证书，重新生成证书可提高与这些工具的兼容性。要重新生成证书，请点击下方的「重新生成证书」按钮。",

  /* --- settings --- */
  "setting.insecureServer": "启用非加密（HTTP）服务器",
  "setting.insecureServerDesc":
    "在下方指定的端口上启用非加密（HTTP）服务器。默认情况下，此插件要求安全的 HTTPS 连接，但在安全环境中，您可以启用非加密服务器以简化与 API 的交互。与 API 的交互仍需使用上方显示的 API 密钥。在任何情况下都不建议将此服务暴露到互联网，特别是在启用此功能时！",
  "setting.resetCrypto": "重置所有加密信息",
  "setting.resetCryptoDesc":
    "点击此按钮将重新生成您的证书、私钥、公钥和 API 密钥。点击后此设置面板将关闭。",
  "setting.resetCryptoBtn": "重置所有加密",
  "setting.regenerateCert": "重新生成证书",
  "setting.regenerateCertDesc":
    "点击此按钮将重新生成您的证书、私钥和公钥，但您的 API 密钥将保持不变。点击后此设置面板将关闭。",
  "setting.regenerateCertBtn": "重新生成证书",
  "setting.restoreDefaults": "恢复默认设置",
  "setting.restoreDefaultsDesc":
    "点击此按钮将重置此插件的设置为默认值。点击后此设置面板将关闭。",
  "setting.restoreDefaultsBtn": "恢复默认",
  "setting.advancedSettings": "显示高级设置",
  "setting.advancedSettingsDesc":
    "高级设置可能带来安全风险，可能降低您的环境安全性。",
  "setting.advancedSettingsHeading": "高级设置",
  "setting.enableSecureServer": "启用加密（HTTPS）服务器",
  "setting.enableSecureServerDesc":
    "控制是否启用 HTTPS 服务器。您几乎肯定希望保持此开关的默认状态（「开」），但在排查问题时可能希望将其关闭。",
  "setting.securePort": "加密（HTTPS）服务器端口",
  "setting.securePortDesc":
    "配置 REST API 监听 HTTPS 连接的端口。建议保留默认端口，因为与此 API 集成的工具可能期望使用默认端口。在任何情况下都不建议将此服务直接暴露到互联网。",
  "setting.insecurePort": "非加密（HTTP）服务器端口",
  "setting.apiKey": "API 密钥",
  "setting.certificateHostnames": "证书主机名",
  "setting.certificateHostnamesDesc":
    "要添加到证书 `subjectAltName` 字段的额外主机名列表，每行一个主机名。更改此值后，必须点击上方的「重新生成证书」按钮才能生效。当您需要从运行 Obsidian 之外的主机名访问时，此设置非常有用。",
  "setting.certificate": "证书",
  "setting.publicKey": "公钥",
  "setting.privateKey": "私钥",
  "setting.authorizationHeader": "授权标头",
  "setting.bindingHost": "绑定主机",
  "setting.verboseLogging": "启用详细日志",
  "setting.verboseLoggingDesc":
    "启用后，将在浏览器控制台中记录服务器启动消息和每个请求的单行访问日志。",

  /* --- advanced static text --- */
  "advanced.warning":
    "以下设置可能存在安全风险，仅供了解其作用的人使用。如果您不了解某项设置的用途及其安全影响，请不要更改它。",
  "advanced.noWarranty1":
    "本软件的使用根据 MIT 许可证授权给您，请务必理解该许可证不提供任何担保。完整的许可证文本请参阅 ",
  "advanced.noWarranty2": "。",

  /* --- periods for link sentence endings --- */
  "period": "。",
};

/* ------------------------------------------------------------------ */
/*  Language detection & t() function                                  */
/* ------------------------------------------------------------------ */

function detectLanguage(): string {
  const lang = navigator.language;
  if (lang.startsWith("zh")) return "zh";
  return "en";
}

let currentLang: string = detectLanguage();
const locales: Record<string, StrMap> = { en, zh };

/**
 * Look up a translated string by key.
 *
 * @param key   Dot-path key in the string map (e.g. `"heading.title"`).
 * @param vars  Optional interpolation variables.  Occurrences of
 *              `{name}` in the translated value are replaced with
 *              `String(vars.name)`.
 */
export function t(key: string, vars?: Record<string, string | number>): string {
  const map = locales[currentLang];
  let str = (map && map[key]) ?? (locales["en"]?.[key] ?? key);
  if (vars) {
    for (const [k, v] of Object.entries(vars)) {
      str = str.replace(`{${k}}`, String(v));
    }
  }
  return str;
}

/**
 * Override the current language (useful for testing).
 */
export function setLanguage(lang: string): void {
  if (locales[lang]) {
    currentLang = lang;
  }
}

/**
 * Force re-detection from navigator.language.
 */
export function resetLanguage(): void {
  currentLang = detectLanguage();
}

/**
 * Return the currently active language code.
 */
export function getCurrentLanguage(): string {
  return currentLang;
}
